### ISSUE TITLE
fixtures: "celery_config" conflict with "celery.contrib.pytest"

### ISSUE THREAD

**Issue by slint** [inveniosoftware/pytest-invenio#10]
`celery_config` is an already defined fixture in [`celery.contrib.pytest`](https://github.com/celery/celery/blob/3fe5a20ca655aa3aeed60205b39ede2a21845df0/celery/contrib/pytest.py#L113), which overwrites the one defined in Invenio.

An easy fix is doing `from pytest_invenio.fixtures import celery_config` at the base `conftest.py`, though this is not an optimal solution.

**Comment by ChiaraBi** [comment]
Could it be ok to rename it as ```invenio_celery_config``` or ```celery_cfg```?

**Comment by slint** [comment]
I think it would be better to just override the original celery fixture by doing something like:

```python
@pytest.fixture(scope='module')
def celery_config(celery_config):
    celery_config.update(dict(
        CELERY_ALWAYS_EAGER=True,
        CELERY_CACHE_BACKEND='memory',
        CELERY_EAGER_PROPAGATES_EXCEPTIONS=True,
        CELERY_RESULT_BACKEND='cache',
    ))
    return celery_config
```

This is also advertised [in the docs of the fixture](https://github.com/inveniosoftware/pytest-invenio/blob/01f7bf525ba4156a27d709e0912db52dc7e9e1aa/pytest_invenio/fixtures.py#L117-L119), so I guess it might be the way to go.
