### ISSUE TITLE
Run pytest directly without passing through setup.py

### ISSUE THREAD

**Issue by diegodelemos** [inveniosoftware/pytest-invenio#56]
Currently, all Invenio modules run tests through `setup.py` (for example [Invenio-DB](https://github.com/inveniosoftware/invenio-db/blob/master/setup.cfg#L11)). We should run tests directly with pytest as running through setuptools has side effects such as packages being updated automatically.

While doing this change, and because now we will use pytest directly, we could advocate for the tool and:
- Improve the user-friendliness when tests fail. For example: "If only one test is failing, you can run pytest for a single test with `pytest my_module.py::my_test_function `, for more tips run `pytest --help`". This is would be connected to https://github.com/inveniosoftware/invenio/issues/4037.
- Find what are low-hanging-fruits we could use/implement to improve the testing experience in Invenio.

To do:
- [x] Find a solution for the problem, create a PR for one repo
- [ ] Propagate the change to all repositories with the outcome of https://github.com/inveniosoftware/opensource/issues/69

**Comment by fenekku** [comment]
Linking https://github.com/inveniosoftware/invenio-app-rdm/issues/191 to this.

**Comment by FlorianCassayre** [comment]
https://codimd.web.cern.ch/bRGRFIF0SkW5L7Zire-y3g

**Comment by FlorianCassayre** [comment]
The utilities will be hosted in a separate repository. The latter could be integrated to `inveniosoftware` in the future, but for now will stay in a personal repository.

**Comment by FlorianCassayre** [comment]
Organization replica: [invenio-toaster](https://github.com/invenio-toaster)
We sent patches for all the repositories that could be patched (about 76). Hopefully travis will complete by tomorrow morning, letting us see the results.

**Comment by lnielsen** [comment]
Regarding the example PR, shouldn't this be changed? 

``python -m pytest`` -> ``pytest``

**Comment by FlorianCassayre** [comment]
@lnielsen We had a discussion with Diego [here](https://github.com/inveniosoftware/invenio-db/pull/131#discussion_r475669257). TL;DR `python -m pytest` is slightly safer. In any case this can be configured [here](https://github.com/frankois/batch_modifier/blob/master/batch_modifier/scripts/test_patcher/config.py#L16).

**Comment by lnielsen** [comment]
Got it. Thanks for the explanation. Agree to go with ``python -m ...`` for the test commands in ``./run-tests.sh``. That said, I would still keep developer documentation to the real commands. E.g. in the documentation for how to run a single test, we should say ``pytest tests/tests_module.py::test_function`` and not ``python -m pytest tests/tests_module.py::test_function``.

**Comment by FlorianCassayre** [comment]
That's a good compromise, I agree with that.
