### ISSUE TITLE
fixtures: elasticsearch require but not installed

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/pytest-invenio#6]
There's [an import](https://github.com/inveniosoftware/pytest-invenio/blob/master/pytest_invenio/fixtures.py#L22) from elasticsearch which causes import errors unless you have elasticsearch installed.  But elasticsearch is not installed with invenio-search by default. 

Probably the import needs to be moved into a function to isolate it.

**Comment by dinosk** [comment]
Should we do the same for `invenio-search`? I got an ImportError coming from it when testing:
```
  File "/Users/dinossimpson/.pyenv/versions/2.7/envs/pytest-invenio/lib/python2.7/site-packages/invenio_search/api.py", line 14, in <module>
    from elasticsearch import VERSION as ES_VERSION
ImportError: No module named elasticsearch
```
it imports elasticsearch in [api.py](https://github.com/inveniosoftware/invenio-search/blob/master/invenio_search/api.py#L14)
